score-break-systems: score-break-systems.c
	gcc -oscore-break-systems -g -std=gnu99 -Wall -Wextra -pedantic score-break-systems.c -lgd -lpng -lfreetype -lm

clean:
	rm score-break-systems

.PHONY: clean
